export enum actionTypes {
    // category
    LOAD_CATEGORIES_CALL = 'LOAD_CATEGORIES_CALL',
    LOAD_CATEGORIES_DONE = 'LOAD_CATEGORIES_DONE',
    LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL',

    // me
    LOAD_MY_POSTS_CALL = 'LOAD_MY_POSTS_CALL',
    LOAD_MY_POSTS_DONE = 'LOAD_MY_POSTS_DONE',
    LOAD_MY_POSTS_FAIL = 'LOAD_MY_POSTS_FAIL',

    LOAD_MY_POST_CALL = 'LOAD_MY_POST_CALL',
    LOAD_MY_POST_DONE = 'LOAD_MY_POST_DONE',
    LOAD_MY_POST_FAIL = 'LOAD_MY_POST_FAIL',

    LOAD_MY_CATEGORIES_CALL = 'LOAD_MY_CATEGORIES_CALL',
    LOAD_MY_CATEGORIES_DONE = 'LOAD_MY_CATEGORIES_DONE',
    LOAD_MY_CATEGORIES_FAIL = 'LOAD_MY_CATEGORIES_FAIL',

    LOAD_MY_TAGS_CALL = 'LOAD_MY_TAGS_CALL',
    LOAD_MY_TAGS_DONE = 'LOAD_MY_TAGS_DONE',
    LOAD_MY_TAGS_FAIL = 'LOAD_MY_TAGS_FAIL',

    WRITE_NEW_POST_CALL = 'WRITE_NEW_POST_CALL',
    WRITE_NEW_POST_DONE = 'WRITE_NEW_POST_DONE',
    WRITE_NEW_POST_FAIL = 'WRITE_NEW_POST_FAIL',

    WRITE_POST_CALL = 'WRITE_POST_CALL',
    WRITE_POST_DONE = 'WRITE_POST_DONE',
    WRITE_POST_FAIL = 'WRITE_POST_FAIL',

    EDIT_POST_CALL = 'EDIT_POST_CALL',
    EDIT_POST_DONE = 'EDIT_POST_DONE',
    EDIT_POST_FAIL = 'EDIT_POST_FAIL',

    DELETE_POST_CALL = 'DELETE_POST_CALL',
    DELETE_POST_DONE = 'DELETE_POST_DONE',
    DELETE_POST_FAIL = 'DELETE_POST_FAIL',

    LOAD_MY_MEDIA_FILES_CALL = 'LOAD_MY_MEDIA_FILES_CALL',
    LOAD_MY_MEDIA_FILES_DONE = 'LOAD_MY_MEDIA_FILES_DONE',
    LOAD_MY_MEDIA_FILES_FAIL = 'LOAD_MY_MEDIA_FILES_FAIL',

    UPLOAD_MY_MEDIA_FILES_CALL = 'UPLOAD_MY_MEDIA_FILES_CALL',
    UPLOAD_MY_MEDIA_FILES_DONE = 'UPLOAD_MY_MEDIA_FILES_DONE',
    UPLOAD_MY_MEDIA_FILES_FAIL = 'UPLOAD_MY_MEDIA_FILES_FAIL',

    EDIT_MY_MEDIA_FILES_CALL = 'EDIT_MY_MEDIA_FILES_CALL',
    EDIT_MY_MEDIA_FILES_DONE = 'EDIT_MY_MEDIA_FILES_DONE',
    EDIT_MY_MEDIA_FILES_FAIL = 'EDIT_MY_MEDIA_FILES_FAIL',

    DELETE_MY_MEDIA_FILES_CALL = 'DELETE_MY_MEDIA_FILES_CALL',
    DELETE_MY_MEDIA_FILES_DONE = 'DELETE_MY_MEDIA_FILES_DONE',
    DELETE_MY_MEDIA_FILES_FAIL = 'DELETE_MY_MEDIA_FILES_FAIL',

    EDIT_MY_CATEGORY_CALL = 'EDIT_MY_CATEGORY_CALL',
    EDIT_MY_CATEGORY_DONE = 'EDIT_MY_CATEGORY_DONE',
    EDIT_MY_CATEGORY_FAIL = 'EDIT_MY_CATEGORY_FAIL',

    DELETE_MY_CATEGORY_CALL = 'DELETE_MY_CATEGORY_CALL',
    DELETE_MY_CATEGORY_DONE = 'DELETE_MY_CATEGORY_DONE',
    DELETE_MY_CATEGORY_FAIL = 'DELETE_MY_CATEGORY_FAIL',

    SIDE_MENU_COLLAPSE = 'SIDE_MENU_COLLAPSE',

    LOAD_LIKED_POSTS_CALL = 'LOAD_LIKED_POSTS_CALL',
    LOAD_LIKED_POSTS_DONE = 'LOAD_LIKED_POSTS_DONE',
    LOAD_LIKED_POSTS_FAIL = 'LOAD_LIKED_POSTS_FAIL',

    LOAD_STAT_GENERAL_CALL = 'LOAD_STAT_GENERAL_CALL',
    LOAD_STAT_GENERAL_DONE = 'LOAD_STAT_GENERAL_DONE',
    LOAD_STAT_GENERAL_FAIL = 'LOAD_STAT_GENERAL_FAIL',

    LOAD_STAT_READ_CALL = 'LOAD_STAT_READ_CALL',
    LOAD_STAT_READ_DONE = 'LOAD_STAT_READ_DONE',
    LOAD_STAT_READ_FAIL = 'LOAD_STAT_READ_FAIL',

    LOAD_POSTS_CALL = 'LOAD_POSTS_CALL',
    LOAD_POSTS_DONE = 'LOAD_POSTS_DONE',
    LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL',

    LOAD_SINGLE_POST_CALL = 'LOAD_SINGLE_POST_CALL',
    LOAD_SINGLE_POST_DONE = 'LOAD_SINGLE_POST_DONE',
    LOAD_SINGLE_POST_FAIL = 'LOAD_SINGLE_POST_FAIL',

    LOAD_USERS_POSTS_CALL = 'LOAD_USERS_POSTS_CALL',
    LOAD_USERS_POSTS_DONE = 'LOAD_USERS_POSTS_DONE',
    LOAD_USERS_POSTS_FAIL = 'LOAD_USERS_POSTS_FAIL',

    LOAD_CATEGORY_POSTS_CALL = 'LOAD_CATEGORY_POSTS_CALL',
    LOAD_CATEGORY_POSTS_DONE = 'LOAD_CATEGORY_POSTS_DONE',
    LOAD_CATEGORY_POSTS_FAIL = 'LOAD_CATEGORY_POSTS_FAIL',

    LOAD_TAG_POSTS_CALL = 'LOAD_TAG_POSTS_CALL',
    LOAD_TAG_POSTS_DONE = 'LOAD_TAG_POSTS_DONE',
    LOAD_TAG_POSTS_FAIL = 'LOAD_TAG_POSTS_FAIL',

    LOAD_USER_CATEGORY_POSTS_CALL = 'LOAD_USER_CATEGORY_POSTS_CALL',
    LOAD_USER_CATEGORY_POSTS_DONE = 'LOAD_USER_CATEGORY_POSTS_DONE',
    LOAD_USER_CATEGORY_POSTS_FAIL = 'LOAD_USER_CATEGORY_POSTS_FAIL',

    LOAD_SEARCH_POSTS_CALL = 'LOAD_SEARCH_POSTS_CALL',
    LOAD_SEARCH_POSTS_DONE = 'LOAD_SEARCH_POSTS_DONE',
    LOAD_SEARCH_POSTS_FAIL = 'LOAD_SEARCH_POSTS_FAIL',

    ADD_LIKE_POST_CALL = 'ADD_LIKE_POST_CALL',
    ADD_LIKE_POST_DONE = 'ADD_LIKE_POST_DONE',
    ADD_LIKE_POST_FAIL = 'ADD_LIKE_POST_FAIL',

    REMOVE_LIKE_POST_CALL = 'REMOVE_LIKE_POST_CALL',
    REMOVE_LIKE_POST_DONE = 'REMOVE_LIKE_POST_DONE',
    REMOVE_LIKE_POST_FAIL = 'REMOVE_LIKE_POST_FAIL',

    SET_CURRENT_URL = 'SET_CURRENT_URL',
    // SET_BASE_URL = 'SET_BASE_URL',

    SIGN_IN_PREPARE = 'SIGN_IN_PREPARE',
    SIGN_IN_CALL = 'SIGN_IN_CALL',
    SIGN_IN_DONE = 'SIGN_IN_DONE',
    SIGN_IN_FAIL = 'SIGN_IN_FAIL',
    SIGN_OUT_CALL = 'SIGN_OUT_CALL',
    SIGN_OUT_DONE = 'SIGN_OUT_DONE',
    SIGN_OUT_FAIL = 'SIGN_OUT_FAIL',
    SIGN_UP_CALL = 'SIGN_UP_CALL',
    SIGN_UP_DONE = 'SIGN_UP_DONE',
    SIGN_UP_FAIL = 'SIGN_UP_FAIL',
    ME_CALL = 'ME_CALL',
    ME_DONE = 'ME_DONE',
    ME_FAIL = 'ME_FAIL',

    SET_JWT = 'SET_JWT',

    CHANGE_PASSWORD_CALL = 'CHANGE_PASSWORD_CALL',
    CHANGE_PASSWORD_DONE = 'CHANGE_PASSWORD_DONE',
    CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL',

    CHANGE_INFO_CALL = 'CHANGE_INFO_CALL',
    CHANGE_INFO_DONE = 'CHANGE_INFO_DONE',
    CHANGE_INFO_FAIL = 'CHANGE_INFO_FAIL',

    VERIFY_EMAIL_CALL = 'VERIFY_EMAIL_CALL',
    VERIFY_EMAIL_DONE = 'VERIFY_EMAIL_DONE',
    VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL',

    /** 전자우편 확인 코드 생성 및 전자우편 전송 */
    REQUEST_VERIFY_EMAIL_CALL = 'REQUEST_VERIFY_EMAIL_CALL',
    REQUEST_VERIFY_EMAIL_DONE = 'REQUEST_VERIFY_EMAIL_DONE',
    REQUEST_VERIFY_EMAIL_FAIL = 'REQUEST_VERIFY_EMAIL_FAIL',

    REQUEST_RESET_PASSWORD_CALL = 'REQUEST_RESET_PASSWORD_CALL',
    REQUEST_RESET_PASSWORD_DONE = 'REQUEST_RESET_PASSWORD_DONE',
    REQUEST_RESET_PASSWORD_FAIL = 'REQUEST_RESET_PASSWORD_FAIL',

    RESET_PASSWORD_CALL = 'RESET_PASSWORD_CALL',
    RESET_PASSWORD_DONE = 'RESET_PASSWORD_DONE',
    RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL',

    UNREGISTER_CALL = 'UNREGISTER_CALL',
    UNREGISTER_DONE = 'UNREGISTER_DONE',
    UNREGISTER_FAIL = 'UNREGISTER_FAIL',
}
